# Site settings
title: AIRONotes 
email: 
description: "A place to collect and share our lecture's notes of the master in 'Artificial Intelligence and Robotics' at Sapienza University (Rome)."
baseurl: ""
url: ""
github_username:  AIRONotes

# Build settings
markdown: kramdown
permalink: pretty

# Sitemap
gems:
  - jekyll-sitemap
